config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'tags/index'
  # get 'tags/show'
  # get 'products/index'
  # get 'products/show'
  # get 'brands/index'
  # get 'brands/show'
  # get 'categories/index'
  # get 'categories/show'
  root to: 'products#index'

  get 'categories', to: 'categories#index', as: 'categories'
  get 'categories/:id', to: 'categories#show', id: /\d+/, as: 'category'
  # resource 'products', only: %i[index show]
  get 'products', to: 'products#index', as: 'products'
  get 'products/:id', to: 'products#show', id: /\d+/, as: 'product'

  get 'brands', to: 'brands#index', as: 'brands'
  get 'brands/:id', to: 'brands#show', id: /\d+/, as: 'brand'

  get 'tags', to: 'tags#index', as: 'tags'
  get 'tags/:id', to: 'tags#show', id: /\d+/, as: 'tag'

  get 'search', to: 'products#search', as: 'search'

  resources :pages
  get ':permalink', to: 'pages#permalink', as: 'permalink'
  # For details on the DSL available within this file, see https:/ / guides.rubyonrails.org / routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
# frozen_string_literal: true

class Brand < ApplicationRecord
  has_many :products
  validates :name, presence: true, uniqueness: true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true, uniqueness: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :category
  has_many :product_tags
  has_many :tags, through: :product_tags
  validates :name, :description, presence: true
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :product
  belongs_to :tag
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :product_tags
  has_many :products, through: :product_tags
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
# frozen_string_literal: true

class BrandsController < ApplicationController
  def index
    @brands = Brand.includes(:products).all.page(params[:page])
  end

  def show
    # @pagy, @brand = pagy(Brand.find(params[:id]), item: 9)
    @brand = Brand.find(params[:id])
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @categories = Category.includes(:products).all.page(params[:page])
  end

  def show
    @category = Category.includes(:products).find(params[:id])

    # @category = Kaminari.paginate_array([@category], total_count: @category.size).page(params[:page])
    # @pagy, @category = pagy(@category)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'admin', except: :permalink
  before_action :set_page, only: %i[show edit update destroy]

  def permalink
    @page = Page.find_by(permalink: params[:permalink])

    redirect_to root_path if @page.nil?
  end

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show; end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.all.page(params[:page])
  end

  def show
    @product = Product.includes(:category).find(params[:id])
  end

  def search
    @products = if params[:category_id].blank?
                  Product.where('name LIKE ?',
                                "%#{params[:search_term]}%")
                else
                  Product.where('name LIKE ? AND category_id = ?',
                                "%#{params[:search_term]}%",
                                params[:category_id].to_s)
                end

    @products
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  include Pagy::Backend
  def index
    @tags = Tag.includes(:products).all.page(params[:page])
  end

  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
# frozen_string_literal: true

module BrandsHelper
  include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
  include Pagy::Frontend
end

app/helpers/pages_helper.rb
module PagesHelper
  include Pagy::Frontend
end

app/helpers/products_helper.rb
module ProductsHelper
  include Pagy::Frontend
end

app/helpers/tags_helper.rb
module TagsHelper
  include Pagy::Frontend
end

app/views/brands/index.html.erb
<% if @brands.empty?  %>
  <p>There are no brands available.</p>
<% else%>

<div class="container pagination justify-content-center" >
  <%= paginate @brands, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
</div>

<div class="container-fluid ">
  <div class="row">
    <div class="col">
    </div>
        <div class="col col-8">
        <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Product in Brand</th>
          </tr>
        </thead>
        <% @brands.each do |brand|%>
          <tr>
            <td><%= link_to brand.name.capitalize , brand_path(brand)%></td>
            <td><%= brand.products.size %> </td>
          </tr>
        <% end %>
        </table>
        </div>
    <div class="col">
    </div>
  </div>
</div>

<div class="container pagination justify-content-center" >
  <%= paginate @brands, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
</div>
<% end%>

app/views/brands/show.html.erb
<h2 class="title is-3"><%= @brand.name.capitalize %></h2>
<p class="content is-medium has-text-grey-darker">There are <%= @brand.products.count %> product in this category.</p>
<p class="content is-medium has-text-grey-darker">Product in <%= @brand.name.capitalize %> are: </p>
<% if @brand.products.empty? %>
  <p> There are no products in this brand</p>
<% else%>
<div class="row">
    <% @brand.products.each do |product|%>
      <div class="col ">
          <div class="card border-light mb-3" >
            <img src="<%= product.image_link %>"  alt="Image not found" width="200" height="150" onerror="this.onerror=null;this.src='http://www.purpicks.com/wp-content/uploads/2018/03/lotus-cosmetics-usa-eye-shadow-palette-smokey.png';" />
            <div class="card-body">
              <h5 class="card-title"> <%= product.name.capitalize %></h5>
              <p class="card-text"><strong>Price:</strong> $<%= product.price %></p>
              <p class="card-text"><strong>Made in:</strong> <%= product.country %></p>
              <%= link_to "Find Out More" , product_path(product)%>
            </div>
          </div>
       </div>
      <% end %>
</div>
<% end %>

<p> <%= link_to "Home", root_path%> </p>

app/views/categories/index.html.erb
<% if @categories.empty?  %>
  <p>There are no categories available.</p>
<% else%>
<div class="container pagination justify-content-center" >
  <%= paginate @categories, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
</div>

<div class="container-fluid ">
  <div class="row">
    <div class="col">
    </div>
        <div class="col col-8">
        <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Product in Category</th>
          </tr>
        </thead>
        <% @categories.each do |category|%>
          <tr>
          <td><%= link_to category.name.capitalize , category_path(category)%></td>
          <td><%= category.products.size %> </td>
          </tr>
        <% end %>
        </table>
        </div>
    <div class="col">
    </div>
  </div>
</div>


<div class="container pagination justify-content-center" >
  <%= paginate @categories, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
</div>
<% end%>

app/views/categories/show.html.erb
<h2 class="title is-3"><%= @category.name.capitalize %></h2>
<p class="content is-medium has-text-grey-darker">There are <%= @category.products.count %> product in this category.</p>
<p class="content is-medium has-text-grey-darker">Product in <%= @category.name.capitalize %> are: </p>

<% if @category.products.empty? %>
  <p> There are no products in this category</p>
<% else%>
  <div class="row">
    <% @category.products.each do |product|%>
      <div class="col ">
    <div class="card border-light mb-3" >
      <img src="<%= product.image_link %>"  alt="Image not found" width="200" height="150" onerror="this.onerror=null;this.src='http://www.purpicks.com/wp-content/uploads/2018/03/lotus-cosmetics-usa-eye-shadow-palette-smokey.png';" />
      <div class="card-body">
        <h5 class="card-title"> <%= product.name.capitalize %></h5>
        <p class="card-text"><strong>Price:</strong> $<%= product.price %></p>
        <p class="card-text"><strong>Made in:</strong> <%= product.country %></p>
        <%= link_to "Find Out More" , product_path(product)%>
      </div>
    </div>
            </div>
      <% end %>
</div>
<% end %>

<p> <%= link_to "Home", root_path%> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Makeup Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">


          <%= link_to "Products", root_path, class: "nav-link"%>
          <%= link_to "Categories", categories_path, class: "nav-link"%>
          <%= link_to "Brands", brands_path,class: "nav-link"%>
          <%= link_to "Tags", tags_path,class: "nav-link"%>
          <%= link_to "About", permalink_path('about_us'),class: "nav-link"%>

          <%= render partial: 'shared/search' %>
  </nav>



  <%= yield %>




  <!-- Footer -->
<footer class="page-footer font-small blue pt-4 navbar-expand-md">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase"> Full Stack Project</h5>
        <p>Makeup Project by Patrick Jiang.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="https://github.com/patrickjcode/Makeup_Project">Github</a>.
          </li>
        </ul>

      </div>
      <!-- Grid column -->


    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright: None
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :permalink %>
    <%= form.text_field :permalink %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/permalink.html.erb
<h2  class="title is-3"><%= @page.title %></h2>

<article>
  <p class="lead"><%= @page.content %></p>

  <figure class="image">
    <img src="https://lh3.googleusercontent.com/Yd7LrL-z77t9d8nZPpKZae59wzsbYu4tutAu55LCFNIfQUIJ4eprLE4bNRFqrNJzze4XoEf_3yztOBW7qOmu_9XSwk99ldBHbHQfxJz09vJ8g8bEIc3dMJMAe0TZR8vc00CwL7elkBl5Mvtz-gX-fGupyHN-r746yAY8S5pigeQYjIG0PJwk5BX-di3pnxboRoexNy0lVY49byw11EIwDH81yzxKzedkV6NeVUW6PKyCtoNenxxcrrH7g6Edjr6AYzDi4WMWuRnyeQeb9OYx-7oeiyJ6b6XgnwxqqfLHWGroDe6nlq4n2vhS4BQyP-tqAV29uqOdxvwQgU8xkJ0mJLEAsrayZhem-T1yWR2jrTPCeBV3gt4G6XnvJx0y4SoFI9Dyl_nb_7Als0s-nObvfySl1VMQedKZkd3pdS4v82ue7J2x3oxippMTJJPcyxMeNWXZxaRq9BqBriI7Yy7YFg9qUN-UT_Sg4qfD-9ZqtHOKFv4j0jyIC_bQ6McrmWqMeVT0likcLf_i9-XztmUqRAPHpXhcFiqJKgYXvNfa2K0Ru0UQ-lpneY_rd2VqjhptWhDFv5QtCoFOC0aRHUrQXp9mabZOGCZ-DX-JtEnc4y1WuhOPVOiOljMSYyHiWWISKzQDX3Ciktpo-DBuxLCU4ZLuwNEsXNep7sFEVLGFiMb8qoGTE1gI_w=w2572-h1530-no" width= "90%">
  </figure>
</article>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/products/index.html.erb
<% if @products.empty?  %>
  <p>There are no categories available.</p>
<% else%>

<div class="container pagination justify-content-center" >
  <%= paginate @products, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
</div>

<div class="row">
    <% @products.each do |product|%>
      <div class="col ">
    <div class="card border-light mb-3" >
      <img src="<%= product.image_link %>"  alt="Image not found" width="200" height="150" onerror="this.onerror=null;this.src='http://www.purpicks.com/wp-content/uploads/2018/03/lotus-cosmetics-usa-eye-shadow-palette-smokey.png';" />
      <div class="card-body">
        <h5 class="card-title"> <%= product.name.capitalize %></h5>
        <p class="card-text"><strong>Price:</strong> $<%= product.price %></p>
        <p class="card-text"><strong>Made in:</strong> <%= product.country %></p>
        <%= link_to "Find Out More" , product_path(product)%>
      </div>
    </div>
            </div>
      <% end %>
</div>

<div class="container pagination justify-content-center" >
  <%= paginate @products, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
</div>

<% end%>

app/views/products/search.html.erb
<% if @products.empty?  %>
  <p>Can't find any product related to your search.</p>
<% else%>
<div class="row">
    <% @products.each do |product|%>
      <div class="col ">
    <div class="card border-light mb-3" >
      <img src="<%= product.image_link %>"  alt="Image not found" width="200" height="150" onerror="this.onerror=null;this.src='http://www.purpicks.com/wp-content/uploads/2018/03/lotus-cosmetics-usa-eye-shadow-palette-smokey.png';" />
      <div class="card-body">
        <h5 class="card-title"> <%= product.name.capitalize %></h5>
        <p class="card-text"><strong>Price:</strong> $<%= product.price %></p>
        <p class="card-text"><strong>Made in:</strong> <%= product.country %></p>
        <%= link_to "Find Out More" , product_path(product)%>
      </div>
    </div>
            </div>
      <% end %>
</div>
<% end%>

app/views/products/show.html.erb
<% if @product.nil?  %>
  <p>There are no categories available.</p>
<% else%>
<div class="container-fluid ">
  <div class="row">
    <div class="col-sm-6">
          <figure class="">
            <img src="<%= @product.image_link %>" alt="Image not found" width="380" height="400" onerror="this.onerror=null;this.src='http://www.purpicks.com/wp-content/uploads/2018/03/lotus-cosmetics-usa-eye-shadow-palette-smokey.png';" />
          </figure>
    </div>
    <div class="col-sm-4">
        <h1 class="title is-2"><%= @product.name %></h1>
        <p class="content is-medium"><strong class="title is-4">Brands:</strong> <%= link_to @product.brand.name.capitalize, brand_path(@product.brand),class: "has-text-primary" %></p>
        <p class="content is-medium"><strong class="title is-4">Description:</strong> <%= @product.description %></p>
        <p class="content is-medium"><strong class="title is-4">Price:</strong> $<%= @product.price %></p>
        <p class="content is-medium"><strong class="title is-4">Category:</strong> <%= link_to @product.category.name.capitalize , category_path(@product.category),class: "has-text-primary"%></p>
        <p class="content is-medium"><strong class="title is-4">Country:</strong> <%= @product.country %></p>
        <p class="content is-medium"><strong class="title is-4">Tags:</strong>
            <% @product.tags.each do |tag| %>
              <%= link_to tag.name.capitalize , tag_path(tag),class: "has-text-primary"%>
            <% end%>
        </p>
    </div>
  </div>
</div>
<% end%>

app/views/shared/_search.html.erb
<%= form_with(url: search_path,local: true,class: "form-inline", method: "get") do %>

  <div class="form-group col-xs-6 form-inline">
       <%= text_field_tag(:search_term,nil,class:"form-control mr-sm-2") %>

      <% category_array = Category.all { |category| [category.name, category.id] } %>
      <%= select_tag(:category_id, options_from_collection_for_select(category_array,'id', 'name'),include_blank: "All",style: "text-transform: capitalize;",class: "form-control") %>
      <%= submit_tag("Search",class:"btn btn-outline-success") %>
  </div>
<% end %>

app/views/tags/index.html.erb
<% if @tags.empty?  %>
  <p>There are no tags available.</p>
<% else%>
<%= paginate @tags %>
  <div class="container-fluid ">
  <div class="row">
    <div class="col">
    </div>
        <div class="col col-8">
        <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Product in Category</th>
          </tr>
        </thead>
        <% @tags.each do |tag|%>
          <tr>
          <td><%= link_to tag.name.capitalize , tag_path(tag)%></td>
          <td><%= tag.products.size %> </td>
          </tr>
        <% end %>
        </table>
        </div>
    <div class="col">
    </div>
  </div>
</div>
<%= paginate @tags %>
<% end%>

app/views/tags/show.html.erb
<h2 class="title is-3"><%= @tag.name.capitalize %></h2>
<p class="content is-medium has-text-grey-darker">There are <%= @tag.products.count %> product in this tag.</p>
<p class="content is-medium has-text-grey-darker">Product in <%= @tag.name.capitalize %> are: </p>

<% if @tag.products.empty? %>
  <p> There are no products in this tag</p>
<% else%>
 <div class="row">
    <% @tag.products.each do |product|%>
      <div class="col ">
          <div class="card border-light mb-3" >
            <img src="<%= product.image_link %>"  alt="Image not found" width="200" height="150" onerror="this.onerror=null;this.src='http://www.purpicks.com/wp-content/uploads/2018/03/lotus-cosmetics-usa-eye-shadow-palette-smokey.png';" />
            <div class="card-body">
              <h5 class="card-title"> <%= product.name.capitalize %></h5>
              <p class="card-text"><strong>Price:</strong> $<%= product.price %></p>
              <p class="card-text"><strong>Made in:</strong> <%= product.country %></p>
              <%= link_to "Find Out More" , product_path(product)%>
            </div>
          </div>
       </div>
      <% end %>
</div>
<% end %>

<p> <%= link_to "Home", root_path%> </p>